# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
from Bio.Seq import Seq
sequence = """ggcaaacagcccgcccggcaccaccatgctcgccctggaggctgcacagctcgacgggccacacttcagctgtctgtacccagatggcgtcttctatgacctggacagctgcaagcattccagctaccctgattcagagggggctcctgactccctgtgggactggactgtggccccaccgtcccagccaccccctatgaagccttcgacccggcagcagccgcttttagccacccccaggctgcccagctctgctacgaaccccccacctacagccctgcagggaacctcgaactggcccccagcctggaggccccggggcctggcctccctgcataccccacggagaacttcgctagccagaccctggttcccccggcatatgccccgtaccccagccctgtgctatcagaggaggaagacttaccgttggacagccctgccctggaggtctcggacagcgagtcggatgaggccctcgtggctggccccgaggggaagggatccgaggcagggactcgcaagaagctgcgcctgtaccagttcctgctggggctactgacgcgcggggacatgcgtgagtgcgtgtggtgggtggagccaggcgccggcgtcttccagttctcctccaagcacaaggaactcctggcgcgccgctggggccagcagaaggggaaccgcaagcgcatgacctaccagaagctggcgcgcgccctccgaaactacgccaagaccggcgagatccgcaaggtcaagcgcaagctcacctaccagttcgacagcgcgctgctgcctgcagtccgccgggcctgagcacacccgaggctcccacctgcggagccgctgggggacctcacgtcccagccaggatccccctggaagaaaaagggcgtccccacactctaggtgataggacttacgcatccccaccttttggggtaaggggagtgctgccctgccataatccccaagcccagcccgggcctgtctgggattccccacttgtgcctggggtcctctgggatttctttgtcatgtacagactccctgggatcctcatgttttgggtgacaggacctatggaccactatactcggggaggcagggtagcagttcttccagaatcccaagagcttctctgggattttcttgtgatatctgattccccagtgaggcctgggacgtttttaagatcgctgtgtgtctgtaaaccctgaatctcatctggggtgggggccctgctggcaaccctgagccctgtccaaggttccctcttgtcagatctgagatttcctagttatgtctggggccctctgggagctgttatcatctcagatctcttcgcccatctatggctgtgttgtcacatctgtcccctcatttttgagatcccccaattctctggaactattctgctgcccctttttatgtgtctggagttccccaatcacatctagggctcctccaagatccttttgtcatgtctgaaatcactcttgagaggtctggggtggaggatggggagtcagtgaaatgtgtcatgtctgggccctgtcagggacacccttgttatatctgggatcctccaatcacatctgagacctcctaggctctccatctgatatgccctttcagggaccccacaaagactgagttctcatggggatcctacccttcctagtgccactccctatggccatgctgaagaccactctggccacgcgactgattttgggtgatcatggcagctccccacccatgtcatttctaaccagaagtctcaaggtcgtcacccccctgccccccaaccgaggccccggtcgctggtggtggtctctttagtgcactgtagcacttggtggtggaggtgtgagggatccacattaacagcaggccatcagctgggcaatggctcacacctgtaatcccagcactttgggaggcgaggcagggggaatggcttgaacccaggcattcaagaccagcctgggcaacataatgagacctcgtctctacaaaacataacaaaaacaattagccgagcgtgggggtgaacacctgtggtcccagctgctcaggaggctgaggtgggaggatctcttgagcccaggaagtaggaggctgtagtgagctgtaatcgtgccactgcactccagcctgggcgacagagtgagacaccgtcttaaaaacaaaaacaaggccgggcacggtggctcatgcctgttgtcccagcactttgggaggccgaggcaggcggatcacgaggtcgagagatcgagaccatcctggccaacatggtgaaaccctgtctctactaaaaatacagaaattagctgggcgtggtggcacgtgcctgtagtcccagctactcgggaggctgaggcaagagaatcgcttgaacgtgggaggcagaggttgcagtgagcctagattgtgccactgcactccagcctgggggacagagcgagactccgtctgaaaataaaaacaacaaaaacagcagaccattcaaaatagggagactttgcataatccagatttctgccttcacttaaaactttggacggtctggagagagtcggccagttttcggtggggggtggggagctggaacaggacagtagcctttcctaatgaggcatttgttctccaatctgccccagtcgctgccatccctggctatctcaccctagcagcttctcaagcctgttggctttagaccactgtataaacccagctggaactgaagcctgggtggactatggagccctggttgggacccccagggagtcaaaggctgcgggccaagaggccagaggtccttgagcctgggtgggcaggtggatctagggtgcatgacttgctgcttcccaaccttagtttgtcccttctgtgaaaaagggagagaaggaggaggaagatctcaaaaagactttccagcccagtgcggtggctcacgcctgtaatcccagcactttgggaggccgatgcaggtggatcacctgaggtaggagttcaagaccagcctgaccaacatagtgaagccccttctctactaaaaatacaaaattagctgggcgtggtggcatgtgcctgtactcccagctacttgggaggctgaggcaggagaatcgcttgaacctgggaggcggaggttgtagtgagctgagatcacaccactgcacaccagcctgggcgacaagagcgaaactccgtctcaaaaaaaaaaaactgttgcagccccgttgagcctttgacaccgcctgaaatccaccccactcccaggaggaggaggaggaaggaatgccaatgacctagagacacgagaagtccatgtggaggcacacagcagctgatggcagagcccaggctgggacctgcccttaagagaatgagtgggaagggggagggaggaagggcaggtaaaacgtcctccccagggccccctgcaacggggaaggtactttttacaaaagctatcattgtcaccctaaatgtggaataaaataagatgcatcgacgtagacaaacctcctgggaccttttgtcagggactgcaatcctgcccctccactgaggccgctggctctcagagacaccgtgacatcacgggtgatgatgagaggagttcaaagagagaattatatgctggcgcggtggctctgtaatcccaacactttggggggccaaggcaggaggatcgcttgagtacaggagtttgaaaccagcctgggcaagatagtgagatccccttcccacccgtctacaaaaaaaataaaaaattagcgggg"""

# Create a Seq object from the sequence
dna_seq = Seq(sequence)

# Pad the sequence if necessary
if len(dna_seq) % 3 != 0:
    dna_seq = dna_seq + Seq('N') * ((3 - (len(dna_seq) % 3)) % 3)

# Transcribe DNA to RNA
rna_seq = dna_seq.transcribe()

# Print results
print(f"RNA sequence: {rna_seq}")
import matplotlib.pyplot as plt


